env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
    arrowFunctions: true
  ecmaVersion: 2021
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
  - react
  - react-hooks
rules:
  no-use-before-define: 'off'
  no-unused-vars: 'off'
  '@typescript-eslint/indent':
    - 2
    - 2
  '@typescript-eslint/no-empty-function':
    - error
    - allow:
        - 'private-constructors'
  '@typescript-eslint/no-use-before-define':
    - error
  'react/react-in-jsx-scope': 'off'
settings:
  react:
    version: detect
